### ISSUE TITLE
Setup your JupyterHub

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/525_group10#17]
Screenshot required:

[Please attach this screen shots from your group for grading](https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/images/2_result.png)

**Comment by dbandrews** [comment]
The link to the server is: http://35.183.49.113/

After you reach the login page for the first time, put in your username, and a new password and click sign in. Remember to note down your password. (edited)

**Comment by dbandrews** [comment]
Just need to add screenshot with Mo's student id in it

**Comment by dbandrews** [comment]
LGTM

**Comment by dbandrews** [comment]
LGTM

**Comment by dbandrews** [comment]
LGTM

**Comment by dbandrews** [comment]
LGTM

**Comment by Andrew-Tan** [comment]
https://github.com/UBC-MDS/525_group10/blob/main/images/2_result.png
