### ISSUE TITLE
Setup the server

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/525_group10#18]
- Login in to the server (instance). The person who spins up the EC2 instance will only have access to the server as he only got the private key. If someone else wants to log in to that instance, you need to get hold of that private key.

- Setup a common data folder to download data, and this folder should be accessible by all users in the JupyterHub. Following commands make a folder and make it accessible to everyone. [Want to learn more about basic UNIX commands?](https://maker.pro/linux/tutorial/basic-linux-commands-for-beginners) 
sudo mkdir -p /srv/data/my_shared_data_folder
sudo chmod 777 /srv/data/my_shared_data_folder/

- If you want a sharing notebook environment, then check out this. if you plan to do [this](https://github.com/gutow/tljh_grp_utils), make sure you install the "members" package in your server run sudo apt-get install members."

- Install AWS CLI. More details [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html).

NOTE:We are installing this in our EC2 instance, but we can install this anywhere to interact with s3. Say you can install it in your local machine and move data to s3.

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
sudo apt install unzip
unzip awscliv2.zip
sudo ./aws/install

- Setup your access key and secret. Do it from your AWS console. Make sure you keep your "Access key ID" & secret key somewhere safe.

- Use these credentials to configure AWS CLI (aws configure). More details here. "Default region" and "output format" you can leave empty.

- AWS cli can be used to interact with a lot of services. Check this out. To get a feel, we will use CLI to interact with s3 and wait for step Wrangle the data in preparation for machine learning

Please attach this screen shots from your group for grading
Make sure you mask the IP address refer [here](.https://www.anysoftwaretools.com/blur-part-picture-mac/)

https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/images/3_result.png

**Comment by dbandrews** [comment]
Done by @Andrew-Tan!.
