### ISSUE TITLE
Setup your S3 bucket and move data

### ISSUE THREAD

**Issue by mgaroub** [UBC-MDS/525_group10#20]
- Screenshot of S3 console with 3 objects/folder in view
https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/images/4_result.png

- Save output file to s3 as "output/ml_data_SYD.csv"
-

**Comment by dbandrews** [comment]
LGTM

**Comment by Andrew-Tan** [comment]
https://github.com/UBC-MDS/525_group10/blob/main/images/4_result.png
